### ISSUE TITLE
App store showing open Button Instead of update button 

### ISSUE THREAD

**Issue by deepak-tcy** [ArtSabintsev/Harpy#154] opened 2017-02-18 06:53 UTC
Use case 

==>Installed app in User's device with version 1.2.2 and released the Version 1.3 on the app Store.After the app is live on the App store ,User is presented with update dialog (HarpyAlertTypeForce) .

==> User clicked on the update button on the Alert and then user navigated to Appstore.
==> In Appstore the app is showing the open button instead of update 
==> User clicked on the open Button shown in the app store .
==> App opens with the previous version .

as user clicked on open on the app store then it needs to check coming back to app that user updated the app or not .

BTW thanks for Developing the Harpy :)

**Comment by ArtSabintsev** [comment] 2017-02-18 07:08
Hi @deepak-tcy 

This is an issue with Apple. For more details please refer to https://github.com/ArtSabintsev/Siren/issues/126.

In essence, the iTunes API is showing an update is available, however, Apple's CDNs have not propagated the executable to the App Store. This is an issue on Apple's end.

The best solution is to drive Harpy using a server-side configuration file that you edit as needed to turn on Harpy on the app side.

Closing the issue, but feel free to respond.

**Closed by ArtSabintsev** 2017-02-18 07:08 UTC

**Comment by YGeorge** [comment] 2017-07-07 09:39
> The best solution is to drive Harpy using a server-side configuration file that you edit as needed to turn on Harpy on the app side.

@ArtSabintsev how can I do that? Could you please provide an example? Thank you.

**Comment by YGeorge** [comment] 2017-07-07 09:41
Also, I've seen that the issue is fixed for Swift version. Do you have a fix for Obj-C too?

**Comment by ArtSabintsev** [comment] 2017-07-07 12:36
@YGeorge this can be achieved with this line https://github.com/ArtSabintsev/Harpy/blob/master/Harpy/Harpy.h#L152, which I forgot to document in the README (I think)

As for the configuration file, there's no tutorial on how to do his. You will simply need to host a versioned JSON file on a server somewhere that you update whenever you want to conditionally turn Harpy on and off.

**Comment by YGeorge** [comment] 2017-07-07 12:41
@ArtSabintsev but how can I connect Harpy with my json or API endpoint? Is it possible? Thanks for option with delay, but it won't help in my case :(

**Comment by ArtSabintsev** [comment] 2017-07-07 14:40
All you need to do is wrap Harpy around a boolean variable that is controlled by a JSON file on your server.
