### ISSUE TITLE
It crashed if I set forceLanguageLocalization 

### ISSUE THREAD

**Issue by hstdt** [ArtSabintsev/Harpy#109] opened 2015-12-23 07:44 UTC
I think the reason is that I'm using cocoapods to Install. In the case localizationString doesn't work,too.

```
_theNewVersionMessage = [NSString stringWithFormat:[self forcedLocalizedStringForKey:@"A new version of %@ is available. Please update to version %@ now."], _appName, currentAppStoreVersion];
```
But `[self forcedLocalizedStringForKey:@"A new version of %@ is available. Please update to version %@ now."]`return `nil` 

```
- (NSString *)forcedLocalizedStringForKey:(NSString *)stringKey
{
    NSString *path = [[NSBundle bundleWithPath:[self bundlePath]] pathForResource:[self forceLanguageLocalization] ofType:@"lproj"];
    return [[NSBundle bundleWithPath:path] localizedStringForKey:stringKey value:stringKey table:@"HarpyLocalizable"];
}
```

```
- (NSString *)bundlePath
{
    return [[NSBundle mainBundle] pathForResource:@"Harpy" ofType:@"bundle"];
}
```
return `nil`

Suggest:Can release note get from `https://itunes.apple.com/lookup` add's to theNewVersionMessage?

**Comment by ArtSabintsev** [comment] 2015-12-23 16:39
Can you show me the exact code you're using to initialize Harpy and the localization, so I can replicate it?

**Comment by hstdt** [comment] 2015-12-24 01:24
I'm using cocoapods,so `[[NSBundle mainBundle] pathForResource:@"Harpy" ofType:@"bundle"];` can not find the Harpy.bundle at pods.

```objc
    [[Harpy sharedInstance] setAppID:itunesId];
    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];
    /* (Optional) Set the Alert Type for your app
     By default, Harpy is configured to use HarpyAlertTypeOption */
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeOption];
    
    [[Harpy sharedInstance] setCountryCode:@"CN"];// ISO-2A country code
    [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageChineseSimplified];
    [[Harpy sharedInstance] checkVersion];
```


It crashed here. `_theNewVersionMessage  = [NSString stringWithFormat:nil, _appName, currentAppStoreVersion]`
![image](https://cloud.githubusercontent.com/assets/10215098/11987729/871b2848-aa1f-11e5-8566-2141dabd09f6.png)

![image](https://cloud.githubusercontent.com/assets/10215098/11987708/2d1387f0-aa1f-11e5-83f5-b9a8a0c41dbc.png)

**Comment by ArtSabintsev** [comment] 2015-12-24 01:26
`cn` is not supported. 

Please look here for supported localizations: https://github.com/ArtSabintsev/Harpy/blob/master/Harpy/Harpy.m#L20-L47

**Comment by ArtSabintsev** [comment] 2015-12-24 01:27
Please use `HarpyLanguageChineseSimplified` or `HarpyLanguageChineseTraditional`

**Comment by hstdt** [comment] 2015-12-24 01:33
@ArtSabintsev   

It crashed without setting CountryCode. CountryCode doesn't matter.
```
[[Harpy sharedInstance] setAppID:itunesId];
    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];
    /* (Optional) Set the Alert Type for your app
     By default, Harpy is configured to use HarpyAlertTypeOption */
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeOption];

    //[[Harpy sharedInstance] setCountryCode:@"CN"];// ISO-2A country code
    [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageChineseSimplified];
    [[Harpy sharedInstance] checkVersion];
```

BTW  CN is okey.
e.g.
`https://itunes.apple.com/lookup?id=590338362&country=CN`
it requires ISO-2A country code
`https://itunes.apple.com/lookup?id=590338362&country= wrong country code`

**Comment by ArtSabintsev** [comment] 2015-12-24 01:37
are you using one existing iTunes ID?

**Comment by ArtSabintsev** [comment] 2015-12-24 01:40
<img width="733" alt="screen shot 2015-12-23 at 8 39 47 pm" src="https://cloud.githubusercontent.com/assets/854860/11987906/5208d1f6-a9b5-11e5-8a5e-1e1bad388048.png">


Just tested on the sample project found in the repo - works just fine.

**Comment by ArtSabintsev** [comment] 2015-12-24 01:40
here's the code I used

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    // Present Window before calling Harpy
    [self.window makeKeyAndVisible];

    // Set the App ID for your app
    [[Harpy sharedInstance] setAppID:@"376771144"]; // iTunes Connect Mobile App ID

    // Set the UIViewController that will present an instance of UIAlertController
    [[Harpy sharedInstance] setPresentingViewController:_window.rootViewController];

    // (Optional) Set the Delegate to track what a user clicked on, or to use a custom UI to present your message.
    [[Harpy sharedInstance] setDelegate:self];

    // (Optional) The tintColor for the alertController
//    [[Harpy sharedInstance] setAlertControllerTintColor:[UIColor purpleColor]];

    // (Optional) Set the App Name for your app
//    [[Harpy sharedInstance] setAppName:@"iTunes Connect Mobile"];

    /* (Optional) Set the Alert Type for your app
     By default, Harpy is configured to use HarpyAlertTypeOption */
    [[Harpy sharedInstance] setAlertType:HarpyAlertTypeOption];

    /* (Optional) If your application is not available in the U.S. App Store, you must specify the two-letter
     country code for the region in which your applicaiton is available. */
//    [[Harpy sharedInstance] setCountryCode:@"en-US"];

    /* (Optional) Overrides system language to predefined language.
     Please use the HarpyLanguage constants defined in Harpy.h. */
    [[Harpy sharedInstance] setForceLanguageLocalization:HarpyLanguageChineseSimplified];

    // Perform check for new version of your app
    [[Harpy sharedInstance] checkVersion];

    return YES;
}
```

**Comment by hstdt** [comment] 2015-12-24 01:41
If I copy Harpy.bundle to major project,it will not crash.

![image](https://cloud.githubusercontent.com/assets/10215098/11987909/4eed261c-aa22-11e5-9347-2991b8505a68.png)

**Comment by ArtSabintsev** [comment] 2015-12-24 01:44
ah, that's really odd. I'll look into it soon.

**Comment by hstdt** [comment] 2015-12-24 02:17
I create a new project with the same pods,it can find the Harpy.bundle.
So my project's configuration may cause the problem.Or I can manually add Harpy.bundle to mainbundle to solve the problem.

**Comment by hstdt** [comment] 2015-12-24 02:27
https://github.com/CocoaPods/CocoaPods/issues/1186 
The discuss may help.And other bundle files at pods copied into project.so ,maybe there something wrong with podspec setting?But I never used podspec before.

**Comment by ArtSabintsev** [comment] 2015-12-24 02:28
If it can find Harpy.bundle in a new project, the issue is most definitely your project setup. 

You don't need to use a pod spec unless you're creating your own library to be distributed via cocoa pods.

Closing this issue. Feel free to comment if you have any further questions.

Enjoy!

**Closed by ArtSabintsev** 2015-12-24 02:28 UTC
