### ISSUE TITLE
Version length changes (shorter) = crash

### ISSUE THREAD

**Issue by LegoTechApps** [ArtSabintsev/Harpy#134] opened 2016-07-12 09:01 UTC
Hello Harpy team,
thanks for sharing 'Harpy' class.

there is 1 issue make the project crash:
case: **version length changes**  **(became shorter)**
1. Old version is x.x(v)
2. New version is x.x.x(v)

**the app will crash on this line:**
oldVersionComponents[2] integerValue 
**issue:** (**old version** string.length is **>** **new version** string.length)

![screen shot 2016-07-12 at 10 22 55 am](https://cloud.githubusercontent.com/assets/18591535/16761300/34ef1744-4828-11e6-8cad-d1c06d6cdc0f.png)

Regards,
www.LegoTechApps.com

**Comment by ArtSabintsev** [comment] 2016-07-12 13:37
Hi,

Thanks for the message.

Is there any reason you (or your co-workers) are moving from one version system to another? It's non-traditional to do so.

If possible, I would try keeping the same versioning system throughout.

If you go from 1.0.0 -> 2.0, simply go to 2.0.0.

Thoughts?

**Comment by LegoTechApps** [comment] 2016-07-12 17:18
yes, but still be better to secure this case,
so, the following code will fix that case
Enjoy Harpy!


_You are invited to Join/Follow us:
[(https://www.facebook.com/LegoTechApps)]
Facebook:
[www.LegoTechApps.com]_


```
- (void)alertTypeForVersion:(NSString *)currentAppStoreVersion
{    
    // Check what version the update is, major, minor or a patch
    **NSArray *oldVersionComponentsBeforeEqualize = [[self currentVersion] componentsSeparatedByString:@"."];
    NSArray *newVersionComponentsBeforeEqualize = [currentAppStoreVersion componentsSeparatedByString: @"."];**
    
    NSArray * oldVersionComponents = **[self equalizeArray:**oldVersionComponentsBeforeEqualize withArray:newVersionComponentsBeforeEqualize];
    NSArray *newVersionComponents = **[self equalizeArray:**newVersionComponentsBeforeEqualize withArray:oldVersionComponentsBeforeEqualize];

    NSLog(@"oldVersionComponents %@",oldVersionComponents);
    NSLog(@"newVersionComponents %@",newVersionComponents);

    
    BOOL oldVersionComponentIsProperFormat = (2 <= [oldVersionComponents count] && [oldVersionComponents count] <= 4);
    BOOL newVersionComponentIsProperFormat = (2 <= [newVersionComponents count] && [newVersionComponents count] <= 4);

    if (oldVersionComponentIsProperFormat && newVersionComponentIsProperFormat) {
        if ([newVersionComponents[0] integerValue] > [oldVersionComponents[0] integerValue]) { // A.b.c.d
            if (_majorUpdateAlertType) _alertType = _majorUpdateAlertType;
        } else if ([newVersionComponents[1] integerValue] > [oldVersionComponents[1] integerValue]) { // a.B.c.d
            if (_minorUpdateAlertType) _alertType = _minorUpdateAlertType;
        } else if ((newVersionComponents.count > 2) && ([newVersionComponents[2] integerValue] > [oldVersionComponents[2] integerValue])) { // a.b.C.d
           if (_patchUpdateAlertType) _alertType = _patchUpdateAlertType;
        } else if ((newVersionComponents.count > 3) && ([newVersionComponents[3] integerValue] > [oldVersionComponents[3] integerValue])) { // a.b.c.D
            if (_revisionUpdateAlertType) _alertType = _revisionUpdateAlertType;
        }
    }
}

```



```
-(NSArray*) equalizeArray:(NSArray*) A withArray:(NSArray*) B
{
    if (A.count >= B.count)
        return A;
    
    NSMutableArray * newA = [A mutableCopy];
    while (newA.count < B.count)
        [newA addObject:@"0"];
    return newA;
}
```

**Comment by ArtSabintsev** [comment] 2016-07-12 19:11
Ah, I'm not so sure it's worth fixing the library as the library works as advertised. The problem is that you're not adhering to versioning systems. 

With that being said, this isn't the first time this issue has come up, however, the other 2 times it's come up, the developer decided to continue sticking with either a 2-point, 3-point, or 4-point versioning system moving forward. I would suggest doing the same.

While I appreciate the feedback, I do not see any reason to make this change.

**Comment by ArtSabintsev** [comment] 2016-07-13 20:57
Closing this issue.

**Closed by ArtSabintsev** 2016-07-13 20:57 UTC
